[package]
name = "gt_algorithms"
version = "0.1.0"
authors = ["Jeron Aldaron Lau <jeronaldaron@gmail.com>"]
edition = "2021"

[dependencies]
rayon = "1.0"

[dev-dependencies]
criterion = "0.6"

[features]
default = ["use-simd"]
use-simd = []

[[bench]]
name = "ramsey"
harness = false
